### ISSUE TITLE
Изучить возможность отслеживания копирования из буфера обмена

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#100]
Изучить возможность и, если это возможно, реализовать отслеживание таких действий, как копирование данных из буфера обмена. 
Если такой возможности нет, описать, почему, какие пробовались способы.

**Comment by DianaRomanenko** [comment]
Отслеживать факт копирования и вставки в (из) буфер обмена.

**Comment by defrozentruth** [comment]
сделано в #125
