### ISSUE TITLE
Отредактировать docker compose 

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#107]
Комментарий от заказчика: "Не мапьте никогда ничего на порты хоста < 1024 (https://github.com/moevm/mse1h2024-moodle/blob/485d487b27b26a7b5fa3ecf295383b4414ebbf4d/docker-compose.yaml#L56),"

Необходимо откорректировать порты.

**Comment by DaniiLBez** [comment]
Написал отдельный compose для заказчика. Не вижу смысла менять dev окружение. В "prod" версии присутствуют только frontend, backend и mongo. Из открытых портов - 8080 с фронтенда, остальные порты закрыты
