### ISSUE TITLE
Сформировать модели

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#11]
Для всех объектов данных, которые будут использоваться в серверной части, а именно:
1. Сессия (с которой собиралась статистика) - экземпляр статистики
2. Пользователь
Сформировать модели данных для дальнейшего использования в модулях сервера.

**Comment by DaniiLBez** [comment]
Реализованы модели для создания, обновления и получения пользователя, а также для создания и получения объекта статистики согласно предоставленному ранее описанию. Для получения схем необходимо поднять сервер, разворачиваемый в докере и перейти на localhost:8080/docs
