### ISSUE TITLE
Изменить формат оправки времени из мудл

### ISSUE THREAD

**Issue by DaniiLBez** [moevm/mse1h2024-moodle#117]
До этого момента мы хранили время и дату отдельно:
```json
"date": "2024-02-02",
"time": "14:00:00",
```
при добавлении фильтрации я изменил формат представления для избежания лишних проблем с обработкой данных, теперь дата и время хранятся следующим образом:
```JS
"timestamp": new Date("2024-02-02T14:00:00").toISOString()
```
или уже после создания в БД: 
```json
"timestamp": {
        "$date": "2024-02-02T14:00:00.000Z"
},
```

Необходимо исправить формат в скрипте, который собирает данные (использовать стандартный ISO формат, иначе дата не распарсится на сервере)

**Comment by defrozentruth** [comment]
сделано в #111

**Comment by defrozentruth** [comment]
сделано в #124
