### ISSUE TITLE
Создать базовый модуль работы с бд

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#12]
Создать модуль работы с базой данных, который будет включать в себя базовые операции:
1. Создания документов
2. Чтение
3. Редактирование документов
4. Удаление документов

Сделать их универсальными для работы с любыми видами данных и коллекций

**Comment by DaniiLBez** [comment]
Реализованы классы отвечающие за работу с БД для обработки пользователей и данных

**Comment by DianaRomanenko** [comment]
Классы реализованы в ветке, привязанной к задаче. Ветка проверена и смерджена.
