### ISSUE TITLE
Реализовать оптимизированный поиск

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#16]
Реализовать функционал, позволяющий отобрать записи статистики, содержащие определенный набор символов (вводимый на пользователем на стороне интерфейса).
В рамках данной задачи реализовать с заглушкой - то есть не реализовывать взаимодействие с клиентом.

**Comment by DaniiLBez** [comment]
Весь поиск реализован на стороне клиента
