### ISSUE TITLE
Реализовать фильтрацию

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#17]
Реализовать возможность выборки и фильтрации данных с применением различных фильтров.

**Comment by DaniiLBez** [comment]
Не понятно, что конкретно фильтровать и какие фильтры требуются

**Comment by DaniiLBez** [comment]
Добавлена фильтрация по времени и дате. Изменил то, как мы храним дату и время, теперь общий таймстемп, который и используется для сравнения при фильтрации, для проверки работоспособности - поднять backend и mongo компоузом, в swagger есть пример входных данных, можно поиграться, передавая только один из параметров или удаляя оба.

Единственное - при размышлениях над реализацией, посчитал, что проверять по времени, не указывая дату - странно, кроме того, требовало излишнее количество костылей - убрал, так что можно указывать начальный и конечный дни, не указывая время, но нельзя наоборот
