### ISSUE TITLE
Интеграция с модулем бд

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#18]
Реализовать взаимодействие и передачу данных с модулем работы с базой данных.

**Comment by DaniiLBez** [comment]
Описаны эндпоинты, для обработки запросов. Они используют сервисы, описанные ранее для передачи данных в репозитории. Для проверки передачи данных необходимо запустить инстанс БД и Бэкенд (для этого описан docker-compose) и перейти на страницу swagger (на скриншоте пример выполнения запроса на получение статистики), либо воспользоваться утилитой curl
![image](https://github.com/moevm/mse1h2024-moodle/assets/90745021/7b6bd416-60f2-4906-a877-20dd38f0e1d3)
