### ISSUE TITLE
Отредактировать докер файл

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#185]
Необходимо в докер файле поменять порядок команд, чтобы после изменения исходников не приходилось устанавливать зависимости

**Comment by DaniiLBez** [comment]
Считаю, что нужно закрыть этот issue в связи с тем, что сейчас так и происходит, при изменении исключительно исходников, используются кэшированные слои - зависимости не скачиваются повторно:

![image](https://github.com/moevm/mse1h2024-moodle/assets/90745021/428e8f9c-cb4d-4f49-9654-8926f3c44215)
