### ISSUE TITLE
Добавить сбор информации о странице

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#188]
Необходимо каждый раз, когда пользователь загружает страницу, на которой отрабатывает скрипт, отправлять на сервер следующую информацию об этой странице:
1. Наименование страницы
2. Браузер, в котором она запущена 
3. Размеры окна 
4. Весь html страницы

**Comment by AnjeZenda** [comment]
Выгрузка всего html-кода страницы document.documentElement.outerHTML
Размеры окна: document.documentElement.clientWidth, document.documentElement.clientHeight
navigator.userAgent для определения браузера
document.title для названия страницы
