### ISSUE TITLE
Убедиться, что скрипт работает со всеми типами элементов

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#189]
Убедиться, что скрипт работает со всеми типами элементов:
1. Кнопки
2. Radiobutton
3. Textarea
4. Сheckbox

**Comment by AnjeZenda** [comment]
![image](https://github.com/moevm/mse1h2024-moodle/assets/80576026/f1927dee-0ab9-47e1-bf3c-12acbe2916ca)
Все типы элементов работают
