### ISSUE TITLE
Сформировать сценарии использования

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#2]
Для имеющейся use-case диаграммы для каждого кейса сформировать сценарий взаимодействия пользователя с системой. 
Результат выложить на Wiki страницу проекта в раздел [Итерация 1](https://github.com/moevm/mse1h2024-moodle/wiki/Итерация1). 
![use-case](https://github.com/moevm/mse1h2024-moodle/assets/86551020/8efde481-0639-44d4-90bb-ebcaeff60c05)

**Comment by LeraChernyakova** [comment]
В [пользовательских сценариях обновлено следующее:](https://github.com/moevm/mse1h2024-moodle/wiki/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B5-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8):
- Триггер и предусловия в UC-2;
- Альтернативный сценарий №7 в UC-3.

**Comment by DianaRomanenko** [comment]
На текущей итерации сценарии сформированы корректно. Возможно после взаимодействия с заказчиком, они будут откорректированы, но для этого будет создана отдельная задача.
