### ISSUE TITLE
Сформировать прототипы интерфейса

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#3]
С учетом функциональных требований к веб приложению сформировать прототипы интерфейсов. Прототипы интерфейсов необходимо сформировать для следующих страниц:
1. Страница авторизации
2. Страница администрирования (удаление статистики - можно объединить с просмотром статистики для админа, сделав под это отдельную кнопку)
3. Страница просмотра статистики для обычного пользователя (учесть, что на странице просмотра статистики необходимо иметь возможность фильтрации статистики - по курсам, по страницам, по пользователям, по группам - можно дополнить список в ходе выполнения задачи)
На странице просмотра статистик предусмотреть возможность работы с графики и экспорт отчетов в csv и json формат.

К задаче стоит приступить после формирования [сценариев использования](https://github.com/moevm/mse1h2024-moodle/issues/2). Также стоит учесть, что веб приложение будет работать с moodle, поэтому бонусом было бы соблюдение корпоративного стиля moodle.

Ссылку на макеты приложить к задаче и на [страницу в Wiki](https://github.com/moevm/mse1h2024-moodle/wiki/Итерация1).

При формировании прототипов интерфейсов можно использовать материалы, представленные в [презентации](https://bitbucket.org/mark_zaslavskiy/teaching_meta/src/master/slides/ui_mockup_and_uc.pdf?at=master&fileviewer=file-view-default).

**Comment by polinaKoroleva05** [comment]
Ссылка на фигму с прототипом интерфейса

https://www.figma.com/file/uFwFYYwGHrrNUxHwdqOEeL/%D0%9F%D0%BE%D0%BB%D0%B8%D0%BD%D0%B0-%D0%9A%D0%BE%D1%80%D0%BE%D0%BB%D0%B5%D0%B2%D0%B0's-team-library?type=design&node-id=0%3A1&mode=design&t=SJIcjoq7Fxcn7kyO-1

**Comment by DianaRomanenko** [comment]
1. Стоит переместить чекбоксы влево, обычно именно такая форма используется в интерфейсах
2. Также необходимо добавить отдельную страницу "Добавление нового пользователя"

**Comment by DianaRomanenko** [comment]
Прототипы проверены несколькими участниками команды, на их основе описаны постановки 
Возможно будут доработаны некоторые формы после уточнения у заказчика вопросов по поводу процесса авторизации
В случае необходимости доработки будет заведена новая задача
