### ISSUE TITLE
Создание структуры страницы отображения статистики

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#30]
Необходимо реализовать страницу просмотра статистики - то есть главную страницу веб-приложения. В рамках текущей задачи необходимо реализовать только структуру, без заполнения данными. Реализация отображения данных и графиков будет выполнена в рамках других задач.

**Comment by polinaKoroleva05** [comment]
Создан [#58 pullrequest](https://github.com/moevm/mse1h2024-moodle/pull/58), информация о внесенных изменениях описана в нем
