### ISSUE TITLE
Поиск библиотеки

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#36]
Подключить библиотеку для работы с графиками. Зафиксировать в результате задаче, какие графики может отрисовывать библиотека, какой нужен для этого формат данных, какие есть возможность манипуляций с графиками.

**Comment by polinaKoroleva05** [comment]
Создана страничка на [вики](https://github.com/moevm/mse1h2024-moodle/wiki/%D0%93%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-Chart.js)
