### ISSUE TITLE
Реализовать интерфейс работы с графиками

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#38]
На странице просмотра статистики заменить заглушки реальными графиками. Реализовать функционал взаимодействия с графиками:
1. Выбор показателей для отображения
2. Изменение масштаба графика 
3. Выбор конкретных точек на  графике для просмотра их значений

**Comment by polinaKoroleva05** [comment]
Компонент графика создан и настроены оси для отображения в [pull request #151](https://github.com/moevm/mse1h2024-moodle/pull/151)
