### ISSUE TITLE
Реализация недостающих обработчиков

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#41]
Реализовать недостающие обработчики из составленного списка в рамках задачи #40

**Comment by DianaRomanenko** [comment]
После уточнения возможностей библиотеки в рамках реализации недостающих обработчиков можно добавить отслеживание открытости страниц, чтобы была возможность просмотреть, когда пользователь переключался на другие страницы.

**Comment by defrozentruth** [comment]
Выоплнено в #84
