### ISSUE TITLE
Сформировать базу данных

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#8]
Необходимо в соответствие с описанием модели данных создать создать свою базу данных и заполнить своими примерами. Прописать реквизиты, а также зафиксировать их на Wiki.

**Comment by DaniiLBez** [comment]
[#47](https://github.com/moevm/mse1h2024-moodle/pull/47) Добавлен compose файл для локального развертывания mongoDB, данные хранятся локально, поэтому прикреплю скрины в wiki. Для того, чтобы подключиться, можно использовать mongosh или MongoDB Compass (пример будет в wiki)
