### ISSUE TITLE
Реализовать обработку данных для отображения на клиенте

### ISSUE THREAD

**Issue by DianaRomanenko** [moevm/mse1h2024-moodle#93]
На текущий момент данные передаются на клиент в сыром виде, необходимо реализовать модуль обработки информации для записи в бд (например, перевода информации на русский язык).

Это позволит лучше понимать, какие именно действия были выполнены пользователями.

**Comment by DaniiLBez** [comment]
По конкретнее, пожалуйста, что именно не подходит для отображения на клиенте? У нас все вокруг заранее определенной схемы строится. Предобработка данных была бы нужна, если бы мы брали данные из внешней апишки, которую не контролируем. На данный момент мы из мудла собираем данные уже в том виде, в котором кладем в базу и ровно по тем контрактам, что использует фронтенд.

**Comment by DianaRomanenko** [comment]
Данная задача была заведена для преобразования наименований типов событий, но по согласованию с заказчиков в ней больше нет необходимости, тк его устроил тот формат (на английском), в котором данные возвращаются
